// pdf.ts — client-side PDF export (jsPDF, dynamically imported so it stays out of the main bundle).
// Multipage report: cover → exec summary + severity legend → zone progress → findings register
// → methodology/limitations → sign-off.
// Styled with locked Blueprint+teal tokens verbatim (no new colours).
import type { ReportModel } from './reports';

// Hex → [R, G, B]
const hex = (h: string): [number, number, number] => [
  parseInt(h.slice(1, 3), 16),
  parseInt(h.slice(3, 5), 16),
  parseInt(h.slice(5, 7), 16),
];

// Locked token RGB values (SPEC §6.2)
const INK = hex('#1B2A3D');
const NAVY = hex('#1E3A66');
const TEAL = hex('#18837E');
const AMBER = hex('#B5781A');
const RED = hex('#C0492F');
const MUTED = hex('#64748B');
const CANVAS = hex('#EDF1F6');
const HAIRLINE = hex('#D8E1EC');
const WHITE: [number, number, number] = [255, 255, 255];

const SEVERITY_COLOR: Record<string, [number, number, number]> = {
  Critical: RED,
  Major: AMBER,
  Minor: hex('#9AA7B6'),
  Cosmetic: hex('#94A3B8'),
};

const SEVERITY_DEF: Record<string, string> = {
  Critical: 'Affects safety, structural integrity or weather-tightness; fix immediately.',
  Major: 'Affects function or fails to meet spec; fix before handover.',
  Minor: 'Noticeable but does not affect function; fix within agreed time.',
  Cosmetic: 'Surface blemish only; address during snagging.',
};

const PAGE_W = 210;
const PAGE_H = 297;
const ML = 18; // left margin
const MR = 18; // right margin
const MT = 20; // top margin (after header)
const CONTENT_W = PAGE_W - ML - MR;

export async function generatePdf(report: ReportModel, scope: 'project' | 'zone', activeZoneId?: string): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const issues = scope === 'zone' && activeZoneId
    ? report.openIssues.filter((i) => {
        const z = report.project.zones.find((z) => z.id === activeZoneId);
        return z && i.zone === z.name;
      })
    : report.openIssues;

  const zones = scope === 'zone' && activeZoneId
    ? report.zones.filter((z) => z.id === activeZoneId)
    : report.zones;

  const scopeLabel = scope === 'zone' && activeZoneId
    ? (report.project.zones.find((z) => z.id === activeZoneId)?.name ?? 'Zone')
    : 'Whole project';

  let y = 0;

  // ── Header band helper ──
  const drawHeader = (pageTitle: string) => {
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, PAGE_W, 22, 'F');
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...WHITE);
    doc.text('OptiSync', ML, 14);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(180, 195, 215);
    doc.text(pageTitle, PAGE_W - MR, 14, { align: 'right' });
  };

  // ── Footer helper ──
  const drawFooter = (pageNum: number) => {
    doc.setDrawColor(...HAIRLINE);
    doc.line(ML, PAGE_H - 14, PAGE_W - MR, PAGE_H - 14);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(`Generated by OptiSync · OptiSync P Ltd · Confidential`, ML, PAGE_H - 9);
    doc.text(`Page ${pageNum}`, PAGE_W - MR, PAGE_H - 9, { align: 'right' });
  };

  // ────────────────────────────────────────────────────────────────────────
  // PAGE 1 — COVER
  // ────────────────────────────────────────────────────────────────────────
  drawHeader('Progress Report');

  // Teal accent bar
  doc.setFillColor(...TEAL);
  doc.rect(ML, 32, 4, 40, 'F');

  // Project name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...INK);
  const nameLines = doc.splitTextToSize(report.project.name, CONTENT_W - 10) as string[];
  doc.text(nameLines, ML + 10, 46);

  // Scope label
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(`Progress Report · ${scopeLabel}`, ML + 10, 46 + nameLines.length * 8 + 4);

  // Meta block
  y = 80;
  doc.setFillColor(...CANVAS);
  doc.roundedRect(ML, y, CONTENT_W, 74, 3, 3, 'F');

  const meta: [string, string][] = [
    ['Project', report.project.name],
    ['Address', report.project.location],
    ['Client', report.project.client],
    ['Contractor', 'Cairn Refurbishment Ltd'],
    ['Report ID', `RPT-${report.project.id.toUpperCase()}-${report.project.scans.filter((s) => s.status === 'Ready').length.toString().padStart(3, '0')}`],
    ['Scan date', report.date],
    ['Prepared by', 'J. Mackay · Site Supervisor'],
    ['BIM model', `${report.project.bim.file} (LOD ${report.project.bim.lod})`],
    ['Coverage', `${report.coverage}%`],
    ['Accuracy', '±17 mm'],
  ];

  doc.setFontSize(8.5);
  let my = y + 7;
  meta.forEach(([k, v]) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED);
    doc.text(k, ML + 5, my);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...INK);
    doc.text(v, ML + 40, my);
    my += 6.5;
  });

  // Coverage donut placeholder (circle)
  const cx = PAGE_W - MR - 22;
  const cy = y + 37;
  doc.setFillColor(...NAVY);
  doc.circle(cx, cy, 18, 'F');
  doc.setFillColor(...WHITE);
  doc.circle(cx, cy, 12, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...INK);
  doc.text(`${report.coverage}%`, cx, cy + 4, { align: 'center' });

  drawFooter(1);

  // ────────────────────────────────────────────────────────────────────────
  // PAGE 2 — EXECUTIVE SUMMARY + SEVERITY LEGEND
  // ────────────────────────────────────────────────────────────────────────
  doc.addPage();
  drawHeader('Executive Summary');
  y = MT + 8;

  // Section title
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Executive Summary', ML, y);
  y += 8;

  // Summary prose
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...INK);
  const summaryLines = doc.splitTextToSize(report.summary, CONTENT_W) as string[];
  doc.text(summaryLines, ML, y);
  y += summaryLines.length * 4.5 + 8;

  // Severity tally
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Severity Tally', ML, y);
  y += 7;

  const sevs = ['Critical', 'Major', 'Minor', 'Cosmetic'] as const;
  const tileW = CONTENT_W / 4 - 2;
  sevs.forEach((sev, i) => {
    const count = issues.filter((iss) => iss.severity === sev).length;
    const tx = ML + i * (tileW + 2.6);
    doc.setFillColor(...CANVAS);
    doc.roundedRect(tx, y, tileW, 20, 2, 2, 'F');
    doc.setFillColor(...SEVERITY_COLOR[sev]);
    doc.circle(tx + 5, y + 5.5, 2.5, 'F');
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...INK);
    doc.text(String(count), tx + tileW / 2, y + 11, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...SEVERITY_COLOR[sev]);
    doc.text(sev, tx + tileW / 2, y + 17, { align: 'center' });
  });
  y += 26;

  // Severity legend
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Severity Definitions', ML, y);
  y += 7;

  sevs.forEach((sev) => {
    doc.setFillColor(...SEVERITY_COLOR[sev]);
    doc.circle(ML + 2.5, y - 1, 2, 'F');
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...INK);
    doc.text(sev, ML + 7, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(SEVERITY_DEF[sev], ML + 30, y);
    y += 6;
  });

  drawFooter(2);

  // ────────────────────────────────────────────────────────────────────────
  // PAGE 3 — ZONE PROGRESS
  // ────────────────────────────────────────────────────────────────────────
  doc.addPage();
  drawHeader('Zone Progress');
  y = MT + 8;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Progress by Zone', ML, y);
  y += 8;

  zones.forEach((z) => {
    const barW = CONTENT_W - 30;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...INK);
    doc.text(z.name, ML, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(`${z.coverage}%`, PAGE_W - MR, y, { align: 'right' });
    y += 4;
    // Track
    doc.setFillColor(...HAIRLINE);
    doc.roundedRect(ML, y, barW, 4, 2, 2, 'F');
    // Fill
    const fillW = (z.coverage / 100) * barW;
    const fillColor = z.coverage >= 100 ? TEAL : NAVY;
    doc.setFillColor(...fillColor);
    if (fillW > 0) doc.roundedRect(ML, y, fillW, 4, 2, 2, 'F');
    y += 9;
  });

  drawFooter(3);

  // ────────────────────────────────────────────────────────────────────────
  // PAGE 4+ — FINDINGS REGISTER
  // ────────────────────────────────────────────────────────────────────────
  doc.addPage();
  drawHeader('Findings Register');
  y = MT + 8;
  let findingsPage = 4;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Findings Register', ML, y);
  y += 8;

  if (issues.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text('No open findings for this scope.', ML, y);
    y += 8;
  }

  issues.forEach((issue) => {
    // Estimate card height
    const rows: [string, string][] = [
      ['Location', `${issue.zone}${issue.location_detail ? ' — ' + issue.location_detail : ''}`],
      ['Finding', issue.finding ?? issue.title],
      ['Measured', issue.measured ?? '—'],
      ['Tolerance', issue.tolerance ?? '—'],
      ['Deviation', issue.deviation ?? '—'],
      ['Impact', issue.impact ?? '—'],
      ['Action', issue.action ?? '—'],
      ['Responsible', issue.responsible ?? '—'],
      ['Status', `${issue.status} · raised ${issue.raised}`],
    ];

    const lineH = 4.5;
    const cardPad = 5;
    // Rough height estimate
    let estH = 10 + cardPad * 2;
    rows.forEach(([, v]) => {
      const lines = doc.splitTextToSize(v, CONTENT_W - 48) as string[];
      estH += lines.length * lineH + 1.5;
    });
    estH += 6; // header row

    if (y + estH > PAGE_H - 22) {
      drawFooter(findingsPage);
      doc.addPage();
      findingsPage++;
      drawHeader('Findings Register (continued)');
      y = MT + 8;
    }

    // Card background
    doc.setFillColor(...CANVAS);
    doc.roundedRect(ML, y, CONTENT_W, estH, 3, 3, 'F');
    doc.setDrawColor(...HAIRLINE);
    doc.roundedRect(ML, y, CONTENT_W, estH, 3, 3, 'S');

    // Severity dot + ID + title
    doc.setFillColor(...SEVERITY_COLOR[issue.severity]);
    doc.circle(ML + cardPad + 2, y + cardPad + 2, 2.5, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...INK);
    doc.text(`${issue.id} · ${issue.severity}`, ML + cardPad + 7, y + cardPad + 3.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(`Raised ${issue.raised}`, PAGE_W - MR - cardPad, y + cardPad + 3.5, { align: 'right' });

    // Divider
    doc.setDrawColor(...HAIRLINE);
    doc.line(ML + cardPad, y + cardPad + 6, PAGE_W - MR - cardPad, y + cardPad + 6);

    let ry = y + cardPad + 11;
    rows.forEach(([k, v]) => {
      const vLines = doc.splitTextToSize(v, CONTENT_W - 48) as string[];
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...MUTED);
      doc.text(k, ML + cardPad, ry);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...INK);
      doc.text(vLines, ML + 40, ry);
      ry += vLines.length * lineH + 1.5;
    });

    y += estH + 5;
  });

  drawFooter(findingsPage);

  // ────────────────────────────────────────────────────────────────────────
  // FINAL PAGE — METHODOLOGY + SIGN-OFF
  // ────────────────────────────────────────────────────────────────────────
  doc.addPage();
  const lastPage = findingsPage + 1;
  drawHeader('Methodology & Sign-off');
  y = MT + 8;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Methodology & Limitations', ML, y);
  y += 8;

  const methodology = [
    'Geometry captured using iPhone LiDAR (ARKit Scene Reconstruction). Coverage computed by comparing the captured point cloud against the BIM reference model.',
    `BIM reference: ${report.project.bim.file} (LOD ${report.project.bim.lod}, ${report.project.bim.disciplines.join(', ')}). Last aligned ${report.project.bim.last_aligned}.`,
    'Positional accuracy: ±17 mm. Surface defects (cracks, dampness, finish quality) are outside scope of geometric coverage analysis.',
    'Tolerances referenced: NHBC Standards 2024 / Scottish Building Standards where applicable.',
    'This report reflects site conditions at the time of scanning only. Subsequent works are not represented.',
  ];
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...INK);
  methodology.forEach((para) => {
    const lines = doc.splitTextToSize(para, CONTENT_W) as string[];
    doc.text(lines, ML, y);
    y += lines.length * 4.5 + 4;
  });
  y += 6;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Sign-off', ML, y);
  y += 8;

  doc.setFillColor(...CANVAS);
  doc.roundedRect(ML, y, CONTENT_W, 36, 3, 3, 'F');

  const signoffs: [string, string][] = [
    ['Prepared by', 'J. Mackay · Site Supervisor · Cairn Refurbishment Ltd'],
    ['Reviewed by', '——————————————'],
    ['Date', report.date],
    ['Report ID', `RPT-${report.project.id.toUpperCase()}-${report.project.scans.filter((s) => s.status === 'Ready').length.toString().padStart(3, '0')}`],
  ];
  let sy = y + 7;
  signoffs.forEach(([k, v]) => {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MUTED);
    doc.text(k, ML + 5, sy);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...INK);
    doc.text(v, ML + 45, sy);
    sy += 7;
  });

  drawFooter(lastPage);

  return doc.output('blob');
}
