// OptiSync seed data — the single source the app reads (OPTISYNC_DATA_SPEC.md, verbatim
// where the spec gives values). 6 UK projects spanning Early → Complete; 3 deep photo-backed
// (Stirling/Morningside/Leith), 3 light (Hyndland + 2 commercial). State is in-memory and
// reset on refresh; user edits roll up via lib/store's api.update.
//
// Issue `appear`/`clear` are coverage thresholds for the timeline scrubber, calibrated to the
// staged reports in OPTISYNC_DEEP_REPORTS.md (e.g. Leith's 4 snags appear by 94% and clear at
// 100%). Light-project trade lists are derived from the canonical UK trade sequence + stage
// (the spec gives trade tables only for the deep projects).
import type { AppData, Project } from './types';

const projects: Project[] = [
  // ── 1. Stirling Flat Refurbishment — Early · deep ───────────────────────────
  {
    id: 'proj-stirling',
    name: 'Stirling Flat Refurbishment',
    sector: 'Residential',
    type: '2-bed tenement flat, full refurbishment',
    location: "King's Park, Stirling, FK8",
    client: 'J. Boyle (private)',
    area_m2: 68,
    stage: 'Early',
    overall_coverage: 28,
    status: 'On track',
    start_date: '2026-04-13',
    target_handover: '2026-08-07',
    depth: 'deep',
    bim: {
      software: 'Autodesk Revit → IFC export',
      file: 'Stirling_Flat_R2.ifc',
      lod: 200,
      disciplines: ['Architectural'],
      last_aligned: '2026-06-08',
    },
    team: ['A. Patel · Project lead', 'M. Ahmed · Scan/tech', 'Reid Joinery · Main contractor'],
    trades: [
      { name: 'Strip-out', status: 'Done' },
      { name: 'Structural / ceiling repair', status: 'Done' },
      { name: 'First fix electrical', status: 'In progress' },
      { name: 'First fix plumbing', status: 'In progress' },
      { name: 'Plastering & skim', status: 'Not started' },
      { name: 'Second fix (all)', status: 'Not started' },
      { name: 'Kitchen fit', status: 'Not started' },
      { name: 'Bathroom / sanitaryware', status: 'Not started' },
      { name: 'Decoration', status: 'Not started' },
      { name: 'Flooring', status: 'Not started' },
      { name: 'Snagging', status: 'Not started' },
    ],
    zones: [
      { id: 'st-z1', name: 'Living / Kitchen (open-plan)', area_m2: 24, coverage: 35, stage: 'Early', note: 'Stripped; first-fix electrical running' },
      { id: 'st-z2', name: 'Bathroom', area_m2: 6, coverage: 22, stage: 'Early', note: 'Stripped to brick; damp on external wall' },
      { id: 'st-z3', name: 'Bedroom 1', area_m2: 14, coverage: 30, stage: 'Early', note: 'First-fix wiring in' },
      { id: 'st-z4', name: 'Bedroom 2', area_m2: 11, coverage: 25, stage: 'Early', note: 'Stripped; ceiling repair complete' },
      { id: 'st-z5', name: 'Hall / Stair', area_m2: 13, coverage: 28, stage: 'Early', note: 'Joist repair complete; bare' },
    ],
    issues: [
      { id: 'ST-03', severity: 'Critical', zone: 'Living / Kitchen', title: 'Lintel above old opening needs renewal', status: 'Open', raised: '2026-05-26', appear: 0 },
      { id: 'ST-01', severity: 'Major', zone: 'Bathroom', title: 'Penetrating damp, external gable wall', status: 'Open', raised: '2026-05-02', appear: 0 },
      { id: 'ST-02', severity: 'Major', zone: 'Hall / Stair', title: 'Consumer unit undersized for new circuits', status: 'Open', raised: '2026-05-18', appear: 20 },
      { id: 'ST-04', severity: 'Minor', zone: 'Bedroom 2', title: 'Skirting line out of level (pre-plaster)', status: 'Closed', raised: '2026-04-25', closed: '2026-04-29', appear: 0, clear: 8 },
    ],
    scans: [
      { id: 'st-sc1', date: '2026-04-16', coverage: 0, note: 'Pre-start baseline scan vs BIM' },
      { id: 'st-sc2', date: '2026-05-09', coverage: 12, note: 'Post strip-out' },
      { id: 'st-sc3', date: '2026-06-08', coverage: 28, note: 'First-fix progress' },
    ],
    captures: ['p016', 'p018', 'p027', 'p040', 'p055'],
  },

  // ── 2. Morningside Townhouse — Mid · deep · HERO ────────────────────────────
  {
    id: 'proj-morningside',
    name: 'Morningside Townhouse',
    sector: 'Residential',
    type: 'Victorian townhouse, full refurbishment over 3 floors',
    location: 'Morningside, Edinburgh, EH10',
    client: 'Caldwell Property Group',
    area_m2: 142,
    stage: 'Mid',
    overall_coverage: 62,
    status: 'On track',
    start_date: '2026-02-24',
    target_handover: '2026-09-18',
    depth: 'deep',
    bim: {
      software: 'Autodesk Revit → IFC export',
      file: 'Morningside_TH_R4.ifc',
      lod: 300,
      disciplines: ['Architectural', 'MEP'],
      last_aligned: '2026-06-09',
    },
    team: [
      'A. Patel · Project lead',
      'M. Ahmed · Scan/tech',
      'Lothian Build Co · Main contractor',
      'Capital MEP · M&E',
    ],
    trades: [
      { name: 'Strip-out', status: 'Done' },
      { name: 'Structural / ceiling repair', status: 'Done' },
      { name: 'First fix electrical', status: 'Done' },
      { name: 'First fix plumbing', status: 'Done' },
      { name: 'Plastering & skim', status: 'Done' },
      { name: 'Second fix joinery', status: 'In progress' },
      { name: 'Second fix electrical', status: 'In progress' },
      { name: 'Second fix plumbing', status: 'In progress' },
      { name: 'Kitchen fit', status: 'In progress' },
      { name: 'Bathroom / sanitaryware', status: 'In progress' },
      { name: 'Decoration', status: 'In progress' },
      { name: 'Flooring', status: 'Not started' },
      { name: 'Snagging', status: 'Not started' },
    ],
    zones: [
      { id: 'mo-z1', name: 'Bedroom 1', area_m2: 18, coverage: 75, stage: 'Mid', note: 'Plastered, mist-coat done' },
      { id: 'mo-z2', name: 'Kitchen', area_m2: 19, coverage: 70, stage: 'Mid', note: 'Units set; worktop template pending' },
      { id: 'mo-z3', name: 'Bedroom 2', area_m2: 15, coverage: 68, stage: 'Mid', note: 'Second-fix joinery underway' },
      { id: 'mo-z4', name: 'Living Room', area_m2: 28, coverage: 65, stage: 'Mid', note: 'Cornice repair complete' },
      { id: 'mo-z5', name: 'Bedroom 3', area_m2: 13, coverage: 60, stage: 'Mid', note: 'Plastered; awaiting decoration' },
      { id: 'mo-z6', name: 'Hall / Stair / Landing', area_m2: 37, coverage: 58, stage: 'Mid', note: 'Spindles being refitted' },
      { id: 'mo-z7', name: 'Family Bathroom', area_m2: 7, coverage: 55, stage: 'Mid', note: 'First-fix done; wet-wall going up' },
      { id: 'mo-z8', name: 'En-suite', area_m2: 5, coverage: 48, stage: 'Mid', note: 'Tiling started — lippage flagged' },
    ],
    issues: [
      { id: 'MO-01', severity: 'Critical', zone: 'Kitchen', title: 'Boiler flue clearance < regs to new window', status: 'Open', raised: '2026-05-21', appear: 52 },
      { id: 'MO-02', severity: 'Major', zone: 'En-suite', title: 'Wall-tile lippage exceeds 2 mm tolerance', status: 'Open', raised: '2026-06-02', appear: 55 },
      { id: 'MO-03', severity: 'Major', zone: 'Kitchen', title: 'Socket bank 140 mm off BIM position', status: 'Open', raised: '2026-06-04', appear: 57 },
      { id: 'MO-04', severity: 'Minor', zone: 'Bedroom 3', title: 'Patchy mist-coat, second coat needed', status: 'Open', raised: '2026-06-07', appear: 60 },
      { id: 'MO-05', severity: 'Minor', zone: 'Living Room', title: 'Cornice joint to make good', status: 'Closed', raised: '2026-05-12', closed: '2026-05-30', appear: 45, clear: 55 },
    ],
    scans: [
      { id: 'mo-sc1', date: '2026-02-27', coverage: 0, note: 'Baseline vs BIM' },
      { id: 'mo-sc2', date: '2026-03-20', coverage: 18, note: 'Strip-out complete' },
      { id: 'mo-sc3', date: '2026-04-22', coverage: 34, note: 'First fix complete' },
      { id: 'mo-sc4', date: '2026-05-19', coverage: 51, note: 'Plastering complete' },
      { id: 'mo-sc5', date: '2026-06-09', coverage: 62, note: 'Second fix in progress' },
    ],
    captures: ['p015', 'p043', 'p047', 'p035', 'p062'],
  },

  // ── 3. Leith Tenement Flat — Complete · deep · handover ─────────────────────
  {
    id: 'proj-leith',
    name: 'Leith Tenement Flat',
    sector: 'Residential',
    type: '2-bed tenement flat, full refurbishment',
    location: 'Leith, Edinburgh, EH6',
    client: 'Shoreline Lettings Ltd',
    area_m2: 71,
    stage: 'Complete',
    overall_coverage: 100,
    status: 'Complete',
    start_date: '2025-11-10',
    target_handover: '2026-05-30',
    depth: 'deep',
    bim: {
      software: 'Autodesk Revit → IFC + as-built PDF',
      file: 'Leith_Flat_AsBuilt_R6.ifc',
      lod: 350,
      disciplines: ['Architectural', 'MEP'],
      last_aligned: '2026-05-28',
    },
    team: ['A. Patel · Project lead', 'M. Ahmed · Scan/tech', 'Forth Refurb Ltd · Main contractor'],
    trades: [
      { name: 'Strip-out', status: 'Done' },
      { name: 'Structural / ceiling repair', status: 'Done' },
      { name: 'First fix electrical', status: 'Done' },
      { name: 'First fix plumbing', status: 'Done' },
      { name: 'Plastering & skim', status: 'Done' },
      { name: 'Second fix joinery', status: 'Done' },
      { name: 'Second fix electrical', status: 'Done' },
      { name: 'Second fix plumbing', status: 'Done' },
      { name: 'Kitchen fit', status: 'Done' },
      { name: 'Bathroom / sanitaryware', status: 'Done' },
      { name: 'Decoration', status: 'Done' },
      { name: 'Flooring', status: 'Done' },
      { name: 'Snagging', status: 'Done' },
      { name: 'Handover', status: 'Done' },
    ],
    zones: [
      { id: 'le-z1', name: 'Kitchen', area_m2: 15, coverage: 100, stage: 'Complete', note: 'Fitted, tested, signed off' },
      { id: 'le-z2', name: 'Bathroom', area_m2: 6, coverage: 100, stage: 'Complete', note: 'Sanitaryware in, sealed' },
      { id: 'le-z3', name: 'Bedroom 1', area_m2: 14, coverage: 100, stage: 'Complete', note: 'Decorated, carpeted' },
      { id: 'le-z4', name: 'Bedroom 2', area_m2: 12, coverage: 100, stage: 'Complete', note: 'Decorated, carpeted' },
      { id: 'le-z5', name: 'Living Room', area_m2: 16, coverage: 100, stage: 'Complete', note: 'Decorated, flooring laid' },
      { id: 'le-z6', name: 'Hall / Stair', area_m2: 8, coverage: 100, stage: 'Complete', note: 'Decorated, runner fitted' },
    ],
    issues: [
      { id: 'LE-01', severity: 'Major', zone: 'Bathroom', title: 'Silicone bead to bath — re-run', status: 'Closed', raised: '2026-05-12', closed: '2026-05-22', appear: 88, clear: 100 },
      { id: 'LE-02', severity: 'Minor', zone: 'Bedroom 1', title: 'Door catching frame, ease & adjust', status: 'Closed', raised: '2026-05-14', closed: '2026-05-20', appear: 88, clear: 100 },
      { id: 'LE-03', severity: 'Minor', zone: 'Kitchen', title: 'Cabinet door alignment', status: 'Closed', raised: '2026-05-15', closed: '2026-05-21', appear: 88, clear: 100 },
      { id: 'LE-04', severity: 'Minor', zone: 'Living Room', title: 'Paint touch-up to architrave', status: 'Closed', raised: '2026-05-16', closed: '2026-05-23', appear: 88, clear: 100 },
    ],
    scans: [
      { id: 'le-sc1', date: '2025-11-13', coverage: 0, note: 'Baseline vs BIM' },
      { id: 'le-sc2', date: '2025-12-18', coverage: 22, note: 'Strip-out + first fix' },
      { id: 'le-sc3', date: '2026-02-10', coverage: 48, note: 'Plastering complete' },
      { id: 'le-sc4', date: '2026-03-24', coverage: 71, note: 'Second fix progressing' },
      { id: 'le-sc5', date: '2026-05-02', coverage: 94, note: 'Decoration + flooring' },
      { id: 'le-sc6', date: '2026-05-28', coverage: 100, note: 'As-built, snags cleared, handover' },
    ],
    captures: ['p026', 'p070', 'p066', 'p080', 'p051'],
  },

  // ── 4. Hyndland Flat — Mid · light · needs review ───────────────────────────
  {
    id: 'proj-hyndland',
    name: 'Hyndland Flat',
    sector: 'Residential',
    type: '2-bed flat, refurbishment',
    location: 'Hyndland, Glasgow, G12',
    client: 'R. Mackenzie (private)',
    area_m2: 74,
    stage: 'Mid',
    overall_coverage: 74,
    status: 'Needs review',
    start_date: '2026-03-09',
    target_handover: '2026-07-25',
    depth: 'light',
    reviewNote:
      'Latest scan flags a partition wall built 220 mm off the BIM position in the kitchen/hall line — a real deviation surfaced by the manual-tag workflow.',
    bim: {
      software: 'Autodesk Revit → IFC export',
      file: 'Hyndland_Flat_R3.ifc',
      lod: 300,
      disciplines: ['Architectural'],
      last_aligned: '2026-06-06',
    },
    team: ['A. Patel · Project lead', 'M. Ahmed · Scan/tech', 'Clyde Interiors · Contractor'],
    trades: [
      { name: 'Strip-out', status: 'Done' },
      { name: 'Structural / ceiling repair', status: 'Done' },
      { name: 'First fix electrical', status: 'Done' },
      { name: 'First fix plumbing', status: 'Done' },
      { name: 'Plastering & skim', status: 'Done' },
      { name: 'Second fix (all)', status: 'Done' },
      { name: 'Kitchen fit', status: 'Done' },
      { name: 'Bathroom / sanitaryware', status: 'Done' },
      { name: 'Decoration', status: 'In progress' },
      { name: 'Flooring', status: 'In progress' },
      { name: 'Snagging', status: 'Not started' },
    ],
    zones: [
      { id: 'hy-z1', name: 'Bathroom', area_m2: 6, coverage: 80, stage: 'Mid', note: 'Second fix done' },
      { id: 'hy-z2', name: 'Kitchen', area_m2: 16, coverage: 78, stage: 'Mid', note: 'Units in; partition deviation flagged' },
      { id: 'hy-z3', name: 'Living Room', area_m2: 17, coverage: 76, stage: 'Mid', note: 'Flooring started' },
      { id: 'hy-z4', name: 'Bedroom 1', area_m2: 15, coverage: 72, stage: 'Mid', note: 'Decoration underway' },
      { id: 'hy-z5', name: 'Bedroom 2', area_m2: 12, coverage: 70, stage: 'Mid', note: 'Decoration underway' },
      { id: 'hy-z6', name: 'Hall', area_m2: 8, coverage: 66, stage: 'Mid', note: 'Affected by partition deviation' },
    ],
    issues: [
      { id: 'HY-01', severity: 'Critical', zone: 'Hall', title: 'Partition 220 mm off plan — under review', status: 'Open', raised: '2026-06-05', appear: 60 },
      { id: 'HY-02', severity: 'Major', zone: 'Kitchen', title: 'Extract duct route clashes with BIM', status: 'Open', raised: '2026-06-05', appear: 60 },
      { id: 'HY-03', severity: 'Minor', zone: 'Living Room', title: 'Skirting return mitre to make good', status: 'Open', raised: '2026-06-01', appear: 50 },
    ],
    scans: [
      { id: 'hy-sc1', date: '2026-03-12', coverage: 0, note: 'Baseline vs BIM' },
      { id: 'hy-sc2', date: '2026-04-18', coverage: 29, note: 'First fix complete' },
      { id: 'hy-sc3', date: '2026-05-20', coverage: 55, note: 'Second fix progressing' },
      { id: 'hy-sc4', date: '2026-06-05', coverage: 74, note: 'Decoration; partition deviation flagged' },
    ],
    captures: ['p011', 'p048', 'p060', 'p012'],
  },

  // ── 5. Marischal Office Fit-Out — Complete · light · commercial (no photos) ──
  {
    id: 'proj-marischal',
    name: 'Marischal Office Fit-Out',
    sector: 'Commercial',
    type: 'Cat-B office fit-out, single floor',
    location: 'Marischal Square, Aberdeen, AB10',
    client: 'Granite Financial Ltd',
    area_m2: 320,
    stage: 'Complete',
    overall_coverage: 91,
    status: 'On track',
    start_date: '2026-01-20',
    target_handover: '2026-06-27',
    depth: 'light',
    bim: {
      software: 'Autodesk Revit → IFC export',
      file: 'Marischal_FitOut_R5.ifc',
      lod: 300,
      disciplines: ['Architectural', 'MEP'],
      last_aligned: '2026-06-07',
    },
    team: ['A. Patel · Project lead', 'M. Ahmed · Scan/tech', 'North Sea Contracts · Fit-out'],
    trades: [
      { name: 'Strip-out / demolition', status: 'Done' },
      { name: 'Partitions & ceilings', status: 'Done' },
      { name: 'First fix M&E', status: 'Done' },
      { name: 'Drylining & plaster', status: 'Done' },
      { name: 'Second fix M&E', status: 'In progress' },
      { name: 'Joinery & fit-out', status: 'In progress' },
      { name: 'Decoration', status: 'Done' },
      { name: 'Flooring & finishes', status: 'Done' },
      { name: 'Commissioning', status: 'In progress' },
      { name: 'Snagging', status: 'In progress' },
    ],
    zones: [
      { id: 'ma-z1', name: 'Open-plan office', area_m2: 180, coverage: 95, stage: 'Complete', note: 'Furniture in; commissioning' },
      { id: 'ma-z2', name: 'Meeting Room A', area_m2: 24, coverage: 92, stage: 'Complete', note: 'AV second fix done' },
      { id: 'ma-z3', name: 'WC block', area_m2: 26, coverage: 90, stage: 'Complete', note: 'Signed off' },
      { id: 'ma-z4', name: 'Meeting Room B', area_m2: 22, coverage: 90, stage: 'Complete', note: 'Snagging' },
      { id: 'ma-z5', name: 'Kitchenette', area_m2: 14, coverage: 88, stage: 'Mid', note: 'Appliance test outstanding' },
      { id: 'ma-z6', name: 'Reception', area_m2: 54, coverage: 85, stage: 'Mid', note: 'Joinery counter being fitted' },
    ],
    issues: [
      { id: 'MA-01', severity: 'Major', zone: 'Open-plan office', title: 'HVAC commissioning incomplete', status: 'Open', raised: '2026-06-03', appear: 85 },
      { id: 'MA-02', severity: 'Minor', zone: 'Reception', title: 'Reception counter delivery delayed', status: 'Open', raised: '2026-05-28', appear: 80 },
    ],
    scans: [
      { id: 'ma-sc1', date: '2026-01-23', coverage: 0, note: 'Baseline vs BIM' },
      { id: 'ma-sc2', date: '2026-03-04', coverage: 31, note: 'Partitions + first fix' },
      { id: 'ma-sc3', date: '2026-04-15', coverage: 58, note: 'Drylining + M&E' },
      { id: 'ma-sc4', date: '2026-05-19', coverage: 79, note: 'Second fix + fit-out' },
      { id: 'ma-sc5', date: '2026-06-07', coverage: 91, note: 'Commissioning' },
    ],
    captures: [],
  },

  // ── 6. City Quay Warehouse — Complete · light · commercial (no photos) ───────
  {
    id: 'proj-cityquay',
    name: 'City Quay Warehouse',
    sector: 'Commercial',
    type: 'Warehouse → light-industrial unit conversion',
    location: 'City Quay, Dundee, DD1',
    client: 'Tay Logistics Ltd',
    area_m2: 850,
    stage: 'Complete',
    overall_coverage: 82,
    status: 'Needs review',
    start_date: '2025-12-01',
    target_handover: '2026-07-11',
    depth: 'light',
    reviewNote:
      'Fire-stopping gap at a service penetration on the mezzanine, plus an office-pod partition line deviating from the BIM model — both flagged for review.',
    bim: {
      software: 'Autodesk Revit → IFC export',
      file: 'CityQuay_Conversion_R4.ifc',
      lod: 300,
      disciplines: ['Architectural', 'Structural'],
      last_aligned: '2026-06-05',
    },
    team: ['A. Patel · Project lead', 'M. Ahmed · Scan/tech', 'Tayside Industrial · Main contractor'],
    trades: [
      { name: 'Demolition & strip-out', status: 'Done' },
      { name: 'Structure & slab', status: 'Done' },
      { name: 'Cladding & envelope', status: 'Done' },
      { name: 'Roller doors', status: 'Done' },
      { name: 'First fix M&E', status: 'In progress' },
      { name: 'Fire-stopping', status: 'In progress' },
      { name: 'Partitions', status: 'Done' },
      { name: 'Office-pod fit-out', status: 'In progress' },
      { name: 'Decoration', status: 'Not started' },
      { name: 'Snagging', status: 'Not started' },
    ],
    zones: [
      { id: 'cq-z1', name: 'Ground-floor open span', area_m2: 520, coverage: 86, stage: 'Complete', note: 'Slab + cladding done' },
      { id: 'cq-z2', name: 'Loading bay', area_m2: 90, coverage: 84, stage: 'Complete', note: 'Roller doors installed' },
      { id: 'cq-z3', name: 'WC / welfare block', area_m2: 40, coverage: 80, stage: 'Mid', note: 'Second fix outstanding' },
      { id: 'cq-z4', name: 'Office pod', area_m2: 60, coverage: 79, stage: 'Mid', note: 'Partitions up; fit-out pending' },
      { id: 'cq-z5', name: 'Mezzanine', area_m2: 140, coverage: 78, stage: 'Mid', note: 'Fire-stopping gap flagged' },
    ],
    issues: [
      { id: 'CQ-01', severity: 'Critical', zone: 'Mezzanine', title: 'Fire-stopping gap at service penetration', status: 'Open', raised: '2026-06-02', appear: 75 },
      { id: 'CQ-02', severity: 'Major', zone: 'Office pod', title: 'Partition line deviates from BIM', status: 'Open', raised: '2026-05-29', appear: 70 },
    ],
    scans: [
      { id: 'cq-sc1', date: '2025-12-04', coverage: 0, note: 'Baseline vs BIM' },
      { id: 'cq-sc2', date: '2026-02-02', coverage: 27, note: 'Structure + slab' },
      { id: 'cq-sc3', date: '2026-03-30', coverage: 49, note: 'Cladding + envelope' },
      { id: 'cq-sc4', date: '2026-05-08', coverage: 68, note: 'Fit-out started' },
      { id: 'cq-sc5', date: '2026-06-05', coverage: 82, note: 'Fire-stopping flagged' },
    ],
    captures: [],
  },
];

export const SEED: AppData = {
  projects,
  company: {
    name: 'Cairn Refurbishment Ltd',
    companyNo: 'SC512347',
    vat: 'GB 412 7785 09',
    registeredOffice: '14 Constitution Street, Leith, Edinburgh, EH6 7BT',
    established: '2014',
  },
  user: {
    name: 'A. Patel',
    role: 'Project Lead',
    email: 'a.patel@cairnrefurb.co.uk',
    initials: 'AP',
  },
  // Org roster for Team & access (app roles). Distinct from each project's site-team labels.
  team: [
    { id: 'm-ap', name: 'A. Patel', initials: 'AP', role: 'Owner', email: 'a.patel@cairnrefurb.co.uk', trade: 'Project lead' },
    { id: 'm-ma', name: 'M. Ahmed', initials: 'MA', role: 'Admin', email: 'm.ahmed@cairnrefurb.co.uk', trade: 'Scan / tech' },
    { id: 'm-ls', name: 'L. Stewart', initials: 'LS', role: 'Editor', email: 'l.stewart@cairnrefurb.co.uk', trade: 'Site manager' },
    { id: 'm-kd', name: 'K. Dunn', initials: 'KD', role: 'Viewer', email: 'k.dunn@cairnrefurb.co.uk', trade: 'Quantity surveyor' },
  ],
  subscription: {
    plan: 'Business',
    price: '£49',
    period: '/mo',
    renews: '01 Jul 2026',
    used: 6,
    limit: 10,
    tiers: [
      { id: 'free', name: 'Free', price: '£0', period: '/mo', tagline: 'Try OptiSync', features: ['1 project', 'Watermarked reports', 'Community support'] },
      { id: 'starter', name: 'Starter', price: '£19', period: '/mo', tagline: 'Sole traders', features: ['3 projects', 'Unwatermarked reports', 'Email support'] },
      { id: 'business', name: 'Business', price: '£49', period: '/mo', current: true, tagline: 'Growing contractors', features: ['10 projects', 'PDF export + share links', 'Team access (4 seats)', 'Priority support'] },
      { id: 'pro', name: 'Pro', price: '£99', period: '/mo', tagline: 'Multi-site teams', features: ['30 projects', 'Unlimited seats', 'Custom branding on reports', 'BIM auto-align'] },
      { id: 'enterprise', name: 'Enterprise', price: '£149', period: '/mo', tagline: 'Unlimited + priority', features: ['Unlimited projects', 'SSO + audit log', 'Dedicated success manager', 'SLA'] },
    ],
    addons: [
      { label: 'Prepared report (per report)', price: '£300–£750' },
      { label: 'BIM model setup', price: '~£500' },
    ],
  },
  settings: {
    units: 'Metric (m²)',
    dateFormat: 'DD MMM YYYY',
    lidarQuality: 'High',
    autoAlign: true,
    notifications: true,
  },
};
